[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["sithengineer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path="./src/day2.rs"

[dependencies]
rand = "0.7.3"
